using './infra.bicep'

param vaultName = 'mynabster-keyvault'
param functionAppName = 'mynabster-functionapp'
param storageAccountName = 'mynabsterfuncstorage'
param apicName = 'mynabster-apic'
param logicAppName = 'mynabster-logicapp'
param openAIAccountName = 'mynabster-openai'
param ynabAccessToken = '<SET THIS>'
param twilioAccountSid = '<SET THIS>'
param twilioAuthToken = '<SET THIS>'
param twilioPhoneNumber = '<SET THIS>'
param message = '<SET THIS>'
param toPhone = '<SET THIS>'
